[package]
name = "coster"
version = "0.1.0"
authors = ["Luke Frisken <l.frisken@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2"
actix-rt = "1"
serde_derive = "1.0"
serde_json = "1.0"
rust_decimal = "1.3.0"
sled = "0.31.0"
nanoid = "0.3.0"
thiserror = "1.0"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
commodity = { git = "https://github.com/kellpossible/commodity", features = ["serde-support"] }
doublecount = { git = "https://github.com/kellpossible/doublecount", features = ["serde-support"] }
