[package]
name = "coster"
version = "0.1.0"
authors = ["Luke Frisken <l.frisken@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
serde_derive = "1.0"
serde_json = "1.0"
rust_decimal = "1.2.0"
iso4217 = "0.3.2"
sled = "0.31.0"
nanoid = "0.2.0"
thiserror = "1.0"

[dependencies.arrayvec]
version = "0.5"
features = ["serde"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["tera_templates"]