[package]
name = "switch-router"
version = "0.1.0"
authors = ["Luke Frisken <l.frisken@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew-router-min = "0.8.0"
gloo-events = "0.1.1"
web-sys = "0.3"