[package]
name = "gui"
version = "0.1.0"
authors = ["Luke Frisken <l.frisken@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
commodity = { version = "0.3", features = ["serde-support"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
rust_decimal = "1.3.0"
costing = { path = "../costing" }
yew = { version = "0.14", features = ["web_sys"] }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Window", "Navigator", "console"] }
gettext = "0.4"
tr = { version = "0.1", default-features = false, features = ["gettext"] }
rust-embed = "5.5.1"
fluent-langneg = "0.12.1"
unic-langid = "0.8.0"
anyhow = "1.0"
itertools = "0.9"